name: Build 

on: [push]

env:
  IMAGE: hello-world-java

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build
      run: |-
        docker build --cache-from=app -t app .

    - name: Publish
      run: |-
        echo ${HELLO_TOKEN} | docker login -u "vguar+helloworld" --password-stdin quay.io
        docker tag app:latest quay.io/vguar/hello-world-java:latest
        docker push quay.io/vguar/hello-world-java:latest