name: Build 

on: [push]

env:
  IMAGE: hello-world-java

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # - name: Google Auth
    #   run: |-
    #     echo ${{ secrets.GKE_SA_KEY }} | base64 -d > /tmp/account.json
    #     gcloud auth activate-service-account --key-file=/tmp/account.json
    #     gcloud config set project ${{ secrets.GKE_PROJECT }}

    # # Get the GKE credentials so we can deploy to the cluster
    # - run: |-
    #     gcloud auth configure-docker
    #     gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}
    
    # - name: Build
    #   run: |-
    #     docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:dev" .

    # # Push the Docker image to Google Container Registry
    # - name: Publish
    #   run: |-
    #     docker push  "gcr.io/$PROJECT_ID/$IMAGE:dev"



